### ISSUE TITLE
[apply-login-partner-changes] - Partner, not able to build profile

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#499]
**Describe the bug**
When trying to build profile as a Partner I get error of missing fields, and also not able to see a password field

**To Reproduce**

1. Go to APPLY
2. Complete email, select Partner
3. One error is:  screen is flickering, not easy to access Build Profile, it should be automatic but seems I had to click Build Profile button
4. Complete all screen fields
5. Save - Not able to save, showing error of missing fields even I have completed all, and also not able to see Password fields

**Expected behavior**
Build profile must be selected automatically in screen, not flickering, not any click needed.
Password fields must be present in form
Save action must work and profile must be created able to login.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165177168-07e3cd47-444f-4d7b-8380-9ba377db98ca.png)

**Comment by eslamzaaki** [comment]
fixed but take if you have account in mentee with this email but don't have profile then password field will be hidden so you need only to build profile take care we can't make 2 accounts with same email in firebase @robert-dm

**Comment by robert-dm** [comment]
@eslamzaaki issue persists, please check this newuser@gmail.com added by admin as Partner, then goes and tries to build profile for Partner, but also able to click APPLY button, this should not be allowed.

![image](https://user-images.githubusercontent.com/35821871/165936091-9fc459be-2b3f-48d6-9a88-f4b45088eb4f.png)

![image](https://user-images.githubusercontent.com/35821871/165936134-10c0f323-2779-4608-8d09-6533caf1fbd8.png)

**Comment by eslamzaaki** [comment]
I try newuser@gmail.com and it works fine for me just make sure to see if field not filled you will see bottom red line under the input check password is field correctly  must be more than 6 chars with numbers

**Comment by robert-dm** [comment]
Ok worked fine now.  Able to do full partner registration as newuser2@newuser2.com
