### ISSUE TITLE
[apply-login-partner-changes] - APPLY functionality - form hidden, radiobutton disabled

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#500]
**Describe the bug**
As soon as http://localhost:3000/application-page loads, radiobuttons mentee, mentor, partner should be disabled and no form should be displayed below the three buttons

**To Reproduce**

1. Go to http://localhost:3000/application-page
2. User fills email
3. Only after user completes a valid email address (validate is a valid email) will be allowed to select a radio button
4. Only after user selects a radio button, the form is displayed
5. if email address is changed, process restarts (forms disappear, radio buttons are unchecked)

**Expected behavior**
As soon as http://localhost:3000/application-page loads, radiobuttons mentee, mentor, partner should be disabled and no form should be displayed below the three buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165206472-3f4bc6a3-560f-464e-a408-98c59ff7067e.png)

**Comment by eslamzaaki** [comment]
fixed @robert-dm

**Comment by robert-dm** [comment]
Not fixed @eslamzaaki issue persists:

![image](https://user-images.githubusercontent.com/35821871/165935691-a2a3117c-8449-4f0d-a4f5-bab8b23afd97.png)

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
working fine now.
![image](https://user-images.githubusercontent.com/35821871/166113397-2cda1756-c80a-484a-8e40-09c557f57d47.png)
