### ISSUE TITLE
[apply-login-partner-changes] - Export mentor account data OR mentee account data in admin view

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#505]
**Describe the bug**
cannot export mentor account data or mentee account data

**To Reproduce**

1. Go to admin
2. Click on export mentor data, or export mentee data in admin dashboard
3. See error

**Expected behavior**
excel should be exported with all data for mentor and mentee users

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165937106-ba74288f-5922-4c9c-aa51-418418519910.png)

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
Still failing @eslamzaaki 
![image](https://user-images.githubusercontent.com/35821871/166113294-f72f9d43-533f-4443-828a-0126cc2aa381.png)

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
fixed
