### ISSUE TITLE
[apply-login-partner-changes] - Validate email for Partner, not validated.

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#510]
**Describe the bug**
After login as partner, system asks for verification of email, but nothing happens when Confirm button is clicked

**To Reproduce**

1. Go to https://mentee-dev.herokuapp.com/admin
2. Add an email as partner
3. go to https://mentee-dev.herokuapp.com/ click apply
4. enter email added by partner, click partner radio button
5. complete the build profile form
6. go to login as partner
7. validation email message appears, on click confirm it should be validated but nothing happens.

**Expected behavior**
Email should be validated

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/166331400-be7078be-c42d-49e2-ad0d-6622919900a2.png)

**Comment by eslamzaaki** [comment]
fixed @robert-dm

**Comment by robert-dm** [comment]
Tried in localhost, couldn't merge it, but even after email is validated, still failing:  
![image](https://user-images.githubusercontent.com/35821871/167302202-090bf4a9-ddab-4067-aac5-77bdd619bc30.png)

**Comment by eslamzaaki** [comment]
@robert-dm  fixed

**Comment by robert-dm** [comment]
@eslamzaaki not working fine, after click Confirm button now it is showing up
![image](https://user-images.githubusercontent.com/35821871/167498154-37050fde-be23-4042-92b2-94348b3e7c99.png)

**Comment by eslamzaaki** [comment]
@robert-dm  check now

**Comment by robert-dm** [comment]
ok
